Drop MelBase.setDefault API: EEE TTT
This:

@@ -517,4 +512,2 @@ def __init__(self, header, ins=None, *, do_unpack=True):
                              f'{header.recType}')
-        for element in self.__class__.melSet.elements:
-            element.setDefault(self)
         MreRecord.__init__(self, header, ins, do_unpack=do_unpack)

:)

EEE type(self).compare_actions.items()) --> another asymmetry

EEE+from . import utils_constants, SlottedType

+    """Metaclass responsible for adding slots to its instances."""
If the classdict contains a 'melSet' object slots will be populated from that instance. Encapsulates
common MelObject and MelRecord behavior.

split

@@ -254,6 +253,5 @@ def buildPatch(self,log,progress):
                     if not rank.female_title: rank.female_title = rankName
                     if not rank.insignia_path:
-                        # if rank_level was not present it will be None
-                        dds_ = f'generic{rank.rank_level or 0:02d}.dds'
+                        dds_ = f'generic{rank.rank_level:02d}.dds'
                         rank.insignia_path = rf'Menus\Stats\Cobl\{dds_}'

Evolved from MelObject subclass handling MelModel comparison:

class A(object): pass
a = A()
a.__slots__ = [u'a', u'b']
a
<__main__.A object at 0x109761a90>
a.__slots__
[u'a', u'b']

Setting the slots just sets an instance attribute - this was set alright
but had nothing to do with the __dict__ people were using in __eq__

Old friends the __slots__

I had tried adding a cache but should not be needed for a few
100s class creations (note this is on MelSet.init, so runs once)

@@ -488,9 +496,2 @@ def __init__(self, attr, *elements):
                                   self.attr)
-        defaulters_key = tuple(_mel_defaulters.items())
-        # defaulters_key = tuple(
-        #             (k, v) for k, v in self.mel_defaulters.items() if u'.'
-        #             not in k)
-        # defaulters_key = tuple((k, v()) for k, v in mel_defaulters.items())
-        # Zero division due to distributors # FIXME simpler key (does this even work?)
-        if defaulters_key not in MelObject.slot_types:
         class _MelObject(self.__class__._mel_object_base_type):
@@ -505,10 +506,8 @@ def __getattr__(self, missing_attr):
                 except KeyError:
+                    if not missing_attr in self.__class__._key_errors:
                         # https://stackoverflow.com/a/33388198/281545
+                        print(missing_attr)  # '__deepcopy__' !
                     self.__class__._key_errors[missing_attr] += 1
                     raise AttributeError(missing_attr)
-        else:
-            _MelObject = None
-            print(defaulters_key)
-        self._mel_object_type = \
-            MelObject.slot_types.setdefault(defaulters_key, _MelObject)
+        self._mel_object_type = _MelObject

EEE TTT mapFids - CDTA VMAD especially add themselves unconditionally -
what happens with other MelUnions

@@@ -911,4 -926,12 +922,5 @@@
          for element in self.element_mapping.values():
-             element.setDefault(record)
-         if self.fallback: self.fallback.setDefault(record)
+             element.getDefaulters(mel_set_instance)
+         if self.fallback:
+             self.fallback.getDefaulters(mel_set_instance)
 -        # fixme -> still needed??
 -        # This is somewhat hacky. We let all FormID elements set their defaults
 -        # afterwards so that records have integers if possible, otherwise
 -        # mapFids will blow up on unions that haven't been loaded, but contain
 -        # FormIDs and other types in other union alternatives
 -        for element in self.fid_elements:
 -            element.getDefaulters(mel_set_instance)

, required=True?

basic_elements.py: _MelFlags note added required param - move up?

EEEE: why did I change:

@@ -457,3 +455,3 @@ def pack_subrecord_data(self, record):
 #------------------------------------------------------------------------------
-class MelRaceParts(MelNull):
+class MelRaceParts(MelBase):
     """Handles a subrecord array, where each subrecord is introduced by an

MelRaceParts(MelBase) did not use any of MelNull

EEEE

hasattr -> getattr(record, u'enchantment') is not None
EEE

Mopy/bash/patcher/patchers/multitweak_actors.py: search for other such
cases (modPath attr will be a PluginStr (alpha) loaded by a MelString -
see _MelModel defs)

_MelHackyObject(MelObject):
Real solution is we should pass record to mel_default_value()

Mopy/bash/parsers.py:
Mopy/bash/patcher/patchers/preservers.py:
record.get_mel_object_for_group - try to eliminate this - at least
encapsulate in parsers (abc)

Mopy/bash/patcher/patchers/preservers.py: getting closer to absorb the
patchers

----
RecPath: hasattr always True when __getattr__ defined for attr: XXX

https://stackoverflow.com/a/52940910/281545 - monkey patching is not an
option for us

SSS fix for naming tweaks Mopy/bash/bolt.py

It would miss the Tutorial from Oblivion -> Fatigue

@@ -131,2 +131,4 @@ def scanModFile(self,modFile,progress):
                 for p_tweak in poolable_tweaks: # type: MultiTweakItem
+                    if record.fid == (u'Oblivion.esm', 124707):
+                        print(record)
                     if p_tweak.wants_record(record):

Turns out wants record would return False cause one of the stages had no
text - attributes now are always present but may be None - changes the
behavior to return True if any of the leaf attributes is not None
We might want to skip rp_exists altogether as rp_eval will do the job
anyway - those calls for nested structures like quests stages

b'QUST': (u'full', u'stages[i].entries[i].text'),

branch up very quickly

EDIT 2022.03.17 21.21:

@@ -2210,3 +2210,3 @@ class _RP_Subpath(_ARP_Subpath):
     def rp_eval(self, record) -> Iterable:
-        rec_el = getattr(record, self._subpath_attr, None)
+        rec_el = getattr(record, self._subpath_attr)
         return self._next_subpath.rp_eval(rec_el) if rec_el is not None else []
@@ -2225,3 +2225,3 @@ class _RP_LeafSubpath(_ARP_Subpath):
     def rp_eval(self, record):
-        rec_val = getattr(record, self._subpath_attr, None)
+        rec_val = getattr(record, self._subpath_attr)
         return [rec_val] if rec_val is not None else []
@@ -2231,3 +2231,3 @@ def rp_map(self, record, func, *args) -> None:
         attr = getattr(record, s_attr)
-        if attr:
+        if attr is not None:
             setattr(record, s_attr, func(*args, attr))

removing the None default - let it blow if we specify a non existing
attribute

This is due to oblivion.records._AMreLeveledListTes4.loadData setting that
flag

@@ -1037,3 +1037,4 @@ class _lvl_flags(Flags):
     def __init__(self):
-        super().__init__(self._flags_sig, 'flags', self._lvl_flags)
+        super().__init__(self._flags_sig, 'flags', self._lvl_flags,
+                         set_default=0)

TTT make EFID required - maybe we should make both optional??

  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\game\oblivion\records.py", line 562, in <module>
    class MreAlch(MreHasEffects, _ObIcon):
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\game\oblivion\records.py", line 581, in MreAlch
    MelEffectsTes4(),
    ^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\complex_subrecords.py", line 476, in __init__
    MelGroups('effects',
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 474, in __init__
    super(MelGroups, self).__init__(attr, *elements)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 420, in __init__
    group_mel_set = MelSet(*elements)
                    ^^^^^^^^^^^^^^^^^
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\record_structs.py", line 159, in __init__
    element.getDefaulters(self)
  File "C:\Dropbox (Personal)\eclipse_workspaces\python\wrye-bash\Mopy\bash\brec\basic_elements.py", line 743, in getDefaulters
    raise SyntaxError(f'{self} duplicate attr(s) {dups}')
SyntaxError: <bash.brec.basic_elements.MelStruct object at 0x000001FD38320370> duplicate attr(s) {('effect_sig', None, b'REHE')}

patcher_dialog.py  193 PatchExecute:
615041994 function calls (579204573 primitive calls) in 387.602 seconds

Mopy/bash/basher/saves_links.py: note I dropped getTypeCopy as record is
only used in record.getEffectsSummary which shouldn't require a copy.
In MelObject.repr I now display the internal attributes.

MelObject__bool__(self): TTT we need to add also mel_object_providers?

Slotted type SSS

I added a check - during development I ended up duplicating slots in there

SSS FFF get_default_object:

This partly undoes the handling of MelObject in
6022ae74cc058912e0bd6012187fb3f885d71325 by setting the defaults for at
least the MelStructs - neater than adding the nulls in a case by case
basis but more importantly than making random records required. I also
dropped the REHE defaults from 'efit_param' and 'effect_sig' - those must
always be set explicitly when creating record elements. Note we got rid
of the get_empty_object override - good. 'efix_param_info' needs a
better solution certainly.